import '../../mgrs/LogicMgr'
import '../EquipLogic'
import './EquipAttrDetailDefines'
import '../../mgrs/LangMgr'
import '../../basic/GameConst'
import '../../basic/Common'
import '../../protos/proto-bundles'
