import '../../../framework/misc/Annotations'
import '../../logic/Activity/MainSceneActivityLogic'
import '../../mgrs/LogicMgr'
import '../MainScenePageActIconHide'
import '../../../framework/event/EventMgr'
import '../../basic/Events'
import '../../../framework/uiFramework/BaseGenUI'
