import '../../../framework/misc/Annotations'
import '../../../framework/uiFramework/BaseGenUI'
import '../../../framework/ui/UIBindingComponent'
import '../../mgrs/LogicMgr'
import '../../logic/MapLogic'
import './StageHighSpeedRewardItem'
