import '../../../framework/misc/Annotations'
import '../../logic/Role/RoleDefines'
import '../../protos/proto-bundles'
import '../../../framework/storage/LocalStorageMgr'
import '../../../framework/uiFramework/BaseGenUI'
import '../../basic/LocalStorageConst'
