import './gensctips/ActExtraRewardsViewPageGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import './GachaStageRewardContent'
import '../../framework/cfg/CfgMgr'
import '../../framework/cfg/ClientConfigEnum'
