import '../../framework/misc/Annotations'
import '../../framework/ui/BaseCell'
import './gensctips/AllianceWarSubPageScheduleWinnerGenCell'
import '../../framework/ui/UIBindingComponent'
import './gensctips/AllianceWarSubPageSchedule'
import '../mgrs/LogicMgr'
import '../logic/AllianceWarLogic'
import '../protos/proto-bundles'
