import '../../framework/ui/BaseCell'
import '../../framework/misc/Annotations'
import './gensctips/AttributeBaseContentGenCell'
import '../protos/proto-bundles'
import './PlayerAttributePage'
import '../mgrs/LogicMgr'
import '../logic/RoleLogic'
import '../logic/AttributeLogic'
