import './gensctips/BattlePageStageInfoAniGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import '../mgrs/LangMgr'
import '../../framework/cfg/CfgMgr'
import '../../framework/cfg/ClientConfigEnum'
