import './gensctips/FriendBattleRecordPopUpGenUI'
import '../../framework/misc/Annotations'
import '../../framework/uiFramework/BaseUI'
import '../logic/Friend/NewFriendLogic'
import './FriendSysFightCell'
import '../mgrs/LogicMgr'
