import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import './gensctips/FullScreenClickPageGenUI'
import '../../framework/ui/UIBindingComponent'
import '../basic/Common'
import './gensctips/UniversalClickAni'
