import './gensctips/GuildApplyListPageGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import './GuildApplyListContent'
import '../mgrs/LogicMgr'
import '../logic/GuildLogic'
import '../protos/proto-bundles'
import '../basic/Common'
