import '../../framework/ui/BaseCell'
import '../../framework/misc/Annotations'
import './gensctips/GuildWarRolePoolCellGenCell'
import '../basic/GameConst'
import '../basic/Common'
import '../mgrs/LogicMgr'
import '../logic/RoleLogic'
