import '../../framework/ui/BaseCell'
import '../../framework/misc/Annotations'
import './gensctips/GuildWarRewardCellGenCell'
import '../../framework/ui/UIBindingComponent'
import '../../framework/cfg/CfgMgr'
import '../../framework/cfg/ClientConfigEnum'
import './gensctips/AllianceWarRewardItem'
