import './gensctips/GVGMapRankPageGenUI'
import '../../framework/uiFramework/BaseUI'
import '../logic/GVG/GVGDef'
import '../../framework/misc/Annotations'
import '../protos/proto-bundles'
import '../mgrs/LogicMgr'
import './GVGMapRankCell'
import '../logic/GVG/GVGLogic'
