import '../../framework/ui/BaseCell'
import '../../framework/misc/Annotations'
import '../logic/GVG/GVGDef'
import './gensctips/GVGPageDetailCityCellGenCell'
import '../mgrs/LogicMgr'
import '../logic/GVG/GVGLogic'
