import './gensctips/GVGVideoPageGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import '../video/MoviePlayer'
import '../logic/GVG/GVGDef'
import './GVGMainPage'
import '../basic/Events'
