import '../../framework/misc/Annotations'
import '../../framework/ui/BaseCell'
import './gensctips/GVGWorldCityReportRoleCellGenCell'
import '../protos/proto-bundles'
import '../../framework/cfg/ClientConfigEnum'
import '../../framework/cfg/CfgMgr'
import '../basic/GameConst'
