import './gensctips/LoginChengeIDPopUpGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import '../../framework/storage/LocalStorageMgr'
import '../basic/GameConst'
