import './gensctips/MarryReplayPageGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import '../mgrs/LogicMgr'
import '../logic/MarryLogic'
import '../protos/proto-bundles'
import './MarryVideoPage'
