import '../../framework/misc/Annotations'
import '../../framework/ui/BaseCell'
import './gensctips/MarryShopWeddingCellGenCell'
import '../../framework/cfg/CfgMgr'
import '../../framework/cfg/ClientConfigEnum'
