import './gensctips/MercenaryExpeditionHighSpeedPopUpGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import '../../framework/ui/UIBindingComponent'
import '../protos/proto-bundles'
import './gensctips/CommonGachaItem'
import '../basic/GameConst'
