import '../../framework/misc/Annotations'
import '../../framework/ui/BaseCell'
import '../protos/proto-bundles'
import '../mgrs/LogicMgr'
import './gensctips/NewFriendBlackListCellGenCell'
import '../logic/Friend/NewFriendLogic'
import '../mgrs/PacketMgr'
import '../logic/HeadIconLogic'
