import './gensctips/NewFriendApplyListPageGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import '../logic/Friend/NewFriendLogic'
import './NewFriendApplyCell'
import '../mgrs/LogicMgr'
import '../basic/Events'
