import './gensctips/OtherPlayerBuildSysPageGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import '../mgrs/LogicMgr'
import '../logic/BuildSystemLogic'
import '../logic/OtherRoleLogic'
