import '../../framework/misc/Annotations'
import '../basic/GameConst'
import '../logic/FateDataInfo'
import '../logic/FateLogic'
import '../logic/OtherRoleLogic'
import '../mgrs/LogicMgr'
import './FateWearsPage'
