import './gensctips/SkillPageNewGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import './SkillPageDetailContent'
import './SkillPageSetContent'
import '../components/CheckBoxTopChooseAni'
import '../redpoint/RedPointLogic'
