import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import './gensctips/UIBattlefieldChallengeBossGenUI'
import '../../framework/ui/UIBindingComponent'
import '../protos/proto-bundles'
import '../battle/BattleHelper'
import '../basic/Events'
