import './gensctips/WorldWarTeamJoinPageGenUI'
import '../../framework/uiFramework/BaseUI'
import '../../framework/misc/Annotations'
import './GVGChoiceMercenaryListContent'
import '../logic/GVG/GVGDef'
import '../basic/Common'
