import '../logic/BattleLogic'
import '../mgrs/LogicMgr'
import '../../framework/uiFramework/UIMgr'
import '../protos/proto-bundles'
import '../logic/OfflineLogic'
import '../uis/OfflineBattleAccountPopUp3'
import '../uis/LevelUpPopUp'
import './IncludeHandler'
