import '../cfg/CfgMgr'
import '../resource-manager/AssetMgr'
import './UIDef'
import '../../game/uis/gensctips/CommonBlack'
import '../ui/UIBindingComponent'
import './UILayer'
import '../utility/Utility'
import './UIMgr'
